"""Centralized Simplified Chinese UI text."""

TEXT = {
    "system_status": "系统状态", "startup_status": "启动状态", "quick_actions": "快捷操作", "recent_log": "最近日志",
    "open_webui": "打开 Open WebUI", "models": "模型", "chat": "聊天", "memory": "记忆", "settings": "设置",
    "health": "健康检查", "about": "关于", "exit": "退出", "model_selector": "模型选择", "conversation_list": "会话列表",
    "input_box": "输入框", "send": "发送", "clear": "清空", "stop_generate": "停止生成", "new_chat": "新建聊天",
    "save_chat": "保存聊天", "rename_chat": "重命名聊天", "delete_chat": "删除聊天", "close": "关闭", "memory_list": "记忆列表",
    "add": "添加", "edit": "编辑", "delete": "删除", "type": "类型", "content": "内容", "importance": "重要性",
    "appearance": "外观", "theme": "主题", "ollama_host": "Ollama 地址", "openwebui_url": "Open WebUI 地址",
    "refresh_interval": "状态刷新间隔（秒）", "health_dashboard": "健康检查面板", "refresh": "刷新", "test": "测试", "save": "保存",
    "ready": "就绪", "checking": "检查中...", "online": "在线", "offline": "离线", "all_ready": "所有服务正常",
    "name": "名称", "id": "标识", "size": "大小", "modified": "修改时间", "no_models": "未找到 Ollama 模型。", "no_conversations": "暂无已保存会话",
    "last_check": "最近检查时间", "no_logs": "暂无日志", "about_title": "关于"
}

CHINESE_TEXT = dict(TEXT)

ENGLISH_TEXT = {
    "system_status": "System Status", "startup_status": "Startup Status", "quick_actions": "Quick Actions", "recent_log": "Recent Log",
    "open_webui": "Open Open WebUI", "models": "Models", "chat": "Chat", "memory": "Memory", "settings": "Settings",
    "health": "Health", "about": "About", "exit": "Exit", "model_selector": "Model Selector", "conversation_list": "Conversation List",
    "input_box": "Input Box", "send": "Send", "clear": "Clear", "stop_generate": "Stop Generate", "new_chat": "New Chat",
    "save_chat": "Save Chat", "rename_chat": "Rename Chat", "delete_chat": "Delete Chat", "close": "Close", "memory_list": "Memory List",
    "add": "Add", "save": "Save", "delete": "Delete", "type": "Type", "content": "Content", "importance": "Importance",
    "appearance": "Appearance", "theme": "Theme", "ollama_host": "Ollama Host", "openwebui_url": "Open WebUI URL",
    "refresh_interval": "Status Refresh Interval", "health_dashboard": "Health Dashboard", "refresh": "Refresh", "test": "Test",
    "ready": "Ready", "checking": "Checking...", "online": "Online", "offline": "Offline", "all_ready": "All Systems Ready",
    "name": "Name", "id": "ID", "size": "Size", "modified": "Modified", "no_models": "No Ollama models found.",
    "no_conversations": "No saved conversations", "last_check": "Last Check Time", "no_logs": "No recent logs", "about_title": "About"
}

PERSONA_CHINESE_TEXT = {
    "persona": "\u4eba\u683c",
    "persona_name": "\u540d\u79f0",
    "persona_description": "\u63cf\u8ff0",
    "persona_style": "\u4ea4\u6d41\u98ce\u683c",
    "persona_rules": "\u884c\u4e3a\u89c4\u5219",
    "edit_persona": "\u7f16\u8f91\u4eba\u683c",
    "save_persona": "\u4fdd\u5b58\u4eba\u683c",
    "reset_persona": "\u6062\u590d\u9ed8\u8ba4",
    "persona_enable": "\u542f\u7528 Persona"
}

PERSONA_ENGLISH_TEXT = {
    "persona": "Persona",
    "persona_name": "Name",
    "persona_description": "Description",
    "persona_style": "Style",
    "persona_rules": "Rules",
    "edit_persona": "Edit Persona",
    "save_persona": "Save Persona",
    "reset_persona": "Reset Default",
    "persona_enable": "Persona Enable"
}

REMOTE_CHINESE_TEXT = {
    "remote_access": "\u8fdc\u7a0b\u8bbf\u95ee",
    "local_address": "\u672c\u5730\u5730\u5740",
    "lan_address": "\u5c40\u57df\u7f51\u5730\u5740",
    "remote_status": "\u8fdc\u7a0b\u72b6\u6001",
    "remote_access_enable": "\u542f\u7528\u8fdc\u7a0b\u8bbf\u95ee",
    "remote_mode": "\u8fdc\u7a0b\u6a21\u5f0f",
    "network_available": "\u7f51\u7edc\u53ef\u7528",
    "security_status": "\u5b89\u5168\u72b6\u6001",
    "local_only": "\u4ec5\u672c\u5730",
    "auth_required_hint": "\u8fdc\u7a0b\u8bbf\u95ee\u9700\u8981\u8ba4\u8bc1\u3002",
    "disabled": "\u5df2\u5173\u95ed",
    "unavailable": "\u4e0d\u53ef\u7528",
    "yes": "\u662f",
    "no": "\u5426",
    "security_checklist": "\u5b89\u5168\u68c0\u67e5\u6e05\u5355",
    "remote_health": "\u8fdc\u7a0b\u5065\u5eb7\u72b6\u6001",
    "remote_access_label": "\u8fdc\u7a0b\u8bbf\u95ee",
    "current_mode": "\u5f53\u524d\u6a21\u5f0f",
    "authentication": "\u8ba4\u8bc1",
    "public_exposure": "\u516c\u7f51\u66b4\u9732",
    "firewall": "\u9632\u706b\u5899",
    "network": "\u7f51\u7edc",
    "local_access": "\u672c\u5730\u8bbf\u95ee",
    "lan_access": "\u5c40\u57df\u7f51\u8bbf\u95ee",
    "security": "\u5b89\u5168",
    "listening_ports": "\u76d1\u542c\u7aef\u53e3",
    "none": "\u65e0",
    "enabled": "\u5df2\u542f\u7528",
    "required": "\u5fc5\u9700",
    "not_configured": "\u672a\u914d\u7f6e",
    "unknown": "\u672a\u77e5",
    "safe": "\u5b89\u5168",
    "warning": "\u8b66\u544a",
    "ok": "\u6b63\u5e38",
    "available": "\u53ef\u7528",
    "local_only_description": "\u4ec5\u5141\u8bb8\u672c\u673a\u8bbf\u95ee\u3002",
    "lan_only_description": "\u672a\u6765\u652f\u6301\u5c40\u57df\u7f51\u8bbf\u95ee\u3002",
    "secure_remote_description": "\u672a\u6765\u652f\u6301\u5b89\u5168\u8fdc\u7a0b\u8bbf\u95ee\u3002",
    "authentication_status": "\u8ba4\u8bc1\u72b6\u6001",
    "configured": "\u5df2\u914d\u7f6e",
    "authentication_not_configured_hint": "\u8ba4\u8bc1\u7cfb\u7edf\u5c1a\u672a\u914d\u7f6e\u3002",
    "lan_ios_readiness": "LAN / iOS \u8bbf\u95ee\u51c6\u5907\u72b6\u6001",
    "ios_same_wifi_status": "iOS \u540c Wi-Fi \u8bbf\u95ee\u72b6\u6001",
    "tailscale_readiness": "Tailscale \u51c6\u5907\u72b6\u6001",
    "remote_safety_status": "\u8fdc\u7a0b\u5b89\u5168\u72b6\u6001",
    "iphone_same_wifi_access": "iPhone \u540c Wi-Fi \u8bbf\u95ee",
    "iphone_same_wifi_note": "\u5982\u679c iPhone \u4e0e\u672c\u7535\u8111\u8fde\u63a5\u540c\u4e00\u4e2a Wi-Fi\uff0c\u672a\u6765\u53ef\u4ee5\u901a\u8fc7 Safari \u8bbf\u95ee\u9884\u89c8\u5730\u5740\u3002\u672c\u7248\u672c\u53ea\u751f\u6210\u5730\u5740\u9884\u89c8\uff0c\u4e0d\u542f\u52a8\u76d1\u542c\u670d\u52a1\uff0c\u4e0d\u4fdd\u8bc1\u5f53\u524d\u53ef\u8bbf\u95ee\u3002",
    "local_preview": "\u672c\u5730\u9884\u89c8",
    "lan_preview": "\u5c40\u57df\u7f51\u9884\u89c8",
    "port_not_configured": "\u7aef\u53e3\u5c1a\u672a\u914d\u7f6e\u3002",
    "no_lan_address": "\u6ca1\u6709\u53ef\u7528\u7684 LAN \u5730\u5740\u3002",
    "ios_compatibility": "iOS \u517c\u5bb9\u6027",
    "safari_supported": "Safari \u652f\u6301",
    "android_required": "\u9700\u8981 Android",
    "same_wifi_access": "\u540c Wi-Fi \u8bbf\u95ee",
    "cellular_access": "\u8702\u7a9d\u7f51\u7edc\u8bbf\u95ee",
    "future_supported": "\u672a\u6765\u652f\u6301",
    "requires_secure_tunnel": "\u9700\u8981\u5b89\u5168\u96a7\u9053",
    "tailscale_note": "\u5982\u9700\u4ece iPhone \u8702\u7a9d\u7f51\u7edc\u8bbf\u95ee\uff0c\u5efa\u8bae\u4f7f\u7528 Tailscale \u6216\u5176\u4ed6\u5b89\u5168\u96a7\u9053\u3002",
    "lan_access_preparation": "LAN \u8bbf\u95ee\u51c6\u5907",
    "lan_readiness": "LAN \u51c6\u5907\u72b6\u6001",
    "ios_access": "iOS \u8bbf\u95ee",
    "not_ready": "\u672a\u51c6\u5907",
    "do_not_expose_warning": "\u4e0d\u8981\u5c06 Aurora \u76f4\u63a5\u66b4\u9732\u5230\u516c\u7f51\u3002\n\u5efa\u8bae\u4f7f\u7528\u5c40\u57df\u7f51\u6216 Tailscale \u7b49\u5b89\u5168\u96a7\u9053\u3002",
    "safety_gate": "\u5b89\u5168\u95e8",
    "remote_safety_check": "\u8fdc\u7a0b\u8bbf\u95ee\u5b89\u5168\u68c0\u67e5",
    "remote_readiness": "\u8fdc\u7a0b\u51c6\u5907\u72b6\u6001",
    "lan": "\u5c40\u57df\u7f51",
    "missing": "\u7f3a\u5931",
    "confirmed": "\u5df2\u786e\u8ba4",
    "not_confirmed": "\u672a\u786e\u8ba4",
    "overall": "\u603b\u4f53\u72b6\u6001",
    "blocked": "\u5df2\u963b\u6b62",
    "security_confirmation": "\u5b89\u5168\u786e\u8ba4",
    "understand_risk": "\u6211\u7406\u89e3\u98ce\u9669",
    "remote_access_warning": "\u8b66\u544a\uff1a\n\u8fdc\u7a0b\u8bbf\u95ee\u4f1a\u5141\u8bb8\u5176\u4ed6\u8bbe\u5907\u8fde\u63a5 Aurora\u3002\n\u8bf7\u786e\u8ba4\u5df2\u914d\u7f6e\u8eab\u4efd\u9a8c\u8bc1\u548c\u7f51\u7edc\u5b89\u5168\u3002",
    "authentication_required_before_remote": "\u542f\u7528\u8fdc\u7a0b\u8bbf\u95ee\u524d\u5fc5\u987b\u914d\u7f6e\u8eab\u4efd\u9a8c\u8bc1\u3002",
    "security_confirmation_required": "\u542f\u7528\u8fdc\u7a0b\u8bbf\u95ee\u524d\u5fc5\u987b\u5b8c\u6210\u5b89\u5168\u786e\u8ba4\u3002",
    "authentication_required": "\u9700\u8981\u8ba4\u8bc1",
    "authentication_type": "\u8ba4\u8bc1\u7c7b\u578b",
    "token_status": "Token \u72b6\u6001",
    "token": "Token",
    "token_auth_future": "Token \u8ba4\u8bc1\uff08\u672a\u6765\uff09",
    "password_auth_future": "\u5bc6\u7801\u8ba4\u8bc1\uff08\u672a\u6765\uff09",
    "auth_secrets_plaintext_warning": "\u8ba4\u8bc1\u4fe1\u606f\u4e0d\u5e94\u4ee5\u660e\u6587\u5f62\u5f0f\u4fdd\u5b58\u3002",
    "token_authentication": "Token \u8ba4\u8bc1",
    "setup_token": "\u8bbe\u7f6e Token",
    "token_last_updated": "Token \u6700\u8fd1\u66f4\u65b0",
    "never_configured": "\u4ece\u672a\u914d\u7f6e",
    "auth_readiness": "\u8ba4\u8bc1\u51c6\u5907\u72b6\u6001",
    "token_missing": "Token \u7f3a\u5931",
    "token_auth_not_configured": "Token \u8ba4\u8bc1\u5c1a\u672a\u914d\u7f6e\u3002",
    "token_setup_note": "\u672c\u7248\u672c\u53ea\u751f\u6210\u4e34\u65f6 Token \u72b6\u6001\uff0c\u4e0d\u4fdd\u5b58\u771f\u5b9e Token\uff0c\u5173\u95ed\u5e94\u7528\u540e\u4e0d\u4fdd\u7559\u3002",
    "never_share_token": "\u4e0d\u8981\u5206\u4eab\u4f60\u7684\u8ba4\u8bc1 Token\u3002",
    "store_credentials_securely": "\u8bf7\u5b89\u5168\u4fdd\u5b58\u8ba4\u8bc1\u51ed\u636e\u3002",
    "credential_storage": "\u51ed\u636e\u5b58\u50a8",
    "storage_status": "\u5b58\u50a8\u72b6\u6001",
    "secure_storage_configured": "\u5df2\u914d\u7f6e\u5b89\u5168\u5b58\u50a8",
    "storage_type": "\u5b58\u50a8\u7c7b\u578b",
    "recommended": "\u63a8\u8350",
    "windows_credential_manager": "Windows \u51ed\u636e\u7ba1\u7406\u5668",
    "future_option": "\u672a\u6765\u9009\u9879",
    "encrypted_local_storage": "\u52a0\u5bc6\u672c\u5730\u5b58\u50a8",
    "not_recommended": "\u4e0d\u63a8\u8350",
    "plain_text_file": "\u660e\u6587\u6587\u4ef6",
    "credential_security": "\u51ed\u636e\u5b89\u5168",
    "no_plain_text_storage": "\u65e0\u660e\u6587\u5b58\u50a8",
    "authentication_framework_ready": "\u8ba4\u8bc1\u6846\u67b6\u5df2\u51c6\u5907",
    "secure_storage_not_configured": "\u5b89\u5168\u5b58\u50a8\u672a\u914d\u7f6e",
    "storage": "\u5b58\u50a8",
    "storage_missing": "\u5b58\u50a8\u7f3a\u5931",
    "secure_credential_storage_required": "\u9700\u8981\u5b89\u5168\u51ed\u636e\u5b58\u50a8\u3002",
    "credential_storage_provider": "\u51ed\u636e\u5b58\u50a8\u63d0\u4f9b\u65b9",
    "provider": "\u63d0\u4f9b\u65b9",
    "status": "\u72b6\u6001",
    "test_status": "\u6d4b\u8bd5\u72b6\u6001",
    "last_check_time": "\u6700\u8fd1\u68c0\u67e5",
    "test_secure_storage": "\u6d4b\u8bd5\u5b89\u5168\u5b58\u50a8",
    "remove_test_credential": "\u5220\u9664\u6d4b\u8bd5\u51ed\u636e",
    "passed": "\u901a\u8fc7",
    "failed": "\u5931\u8d25",
    "available_status": "\u53ef\u7528",
    "unavailable_status": "\u4e0d\u53ef\u7528",
    "secure_storage_unavailable": "\u5b89\u5168\u51ed\u636e\u5b58\u50a8\u4e0d\u53ef\u7528\u3002",
    "windows_credential_manager_note": "Windows Credential Manager \u63d0\u4f9b\u7cfb\u7edf\u7ea7\u5b89\u5168\u51ed\u636e\u5b58\u50a8\u3002"
    ,
    "credential_storage_diagnostics": "\u51ed\u636e\u5b58\u50a8\u8bca\u65ad",
    "availability": "\u53ef\u7528\u6027",
    "last_result": "\u6700\u8fd1\u7ed3\u679c",
    "last_error": "\u6700\u8fd1\u9519\u8bef",
    "command_status": "\u547d\u4ee4\u72b6\u6001",
    "credential_history": "\u51ed\u636e\u5b58\u50a8\u5386\u53f2",
    "no_history": "\u6682\u65e0\u5386\u53f2",
    "open_diagnostics_for_details": "\u8bf7\u67e5\u770b\u8bca\u65ad\u8be6\u60c5\u3002",
    "remote_blocked_storage_unavailable": "\u8fdc\u7a0b\u8bbf\u95ee\u5df2\u963b\u6b62\uff1a\n\u5b89\u5168\u51ed\u636e\u5b58\u50a8\u4e0d\u53ef\u7528\u3002\n\u8bf7\u67e5\u770b\u8bca\u65ad\u8be6\u60c5\u3002"
    ,
    "remote_diagnostics": "\u8fdc\u7a0b\u8bca\u65ad",
    "remote_readiness_summary": "\u8fdc\u7a0b\u51c6\u5907\u6458\u8981",
    "credential_storage_details": "\u51ed\u636e\u5b58\u50a8\u8be6\u60c5",
    "last_operation": "\u6700\u8fd1\u64cd\u4f5c",
    "operation_result": "\u64cd\u4f5c\u7ed3\u679c",
    "duration": "\u8017\u65f6",
    "error_reason": "\u9519\u8bef\u539f\u56e0",
    "suggestion": "\u5efa\u8bae",
    "release_check": "\u53d1\u5e03\u68c0\u67e5",
    "release_check_started": "\u53d1\u5e03\u68c0\u67e5\u5f00\u59cb",
    "release_check_completed": "\u53d1\u5e03\u68c0\u67e5\u5b8c\u6210",
    "startup_diagnostic": "\u542f\u52a8\u8bca\u65ad",
    "features": "\u529f\u80fd",
    "remote_security": "\u8fdc\u7a0b\u5b89\u5168",
    "data_directory_available": "\u6570\u636e\u76ee\u5f55\u53ef\u7528",
    "configuration_valid": "\u914d\u7f6e\u6709\u6548",
    "remote_configuration_valid": "\u8fdc\u7a0b\u914d\u7f6e\u6709\u6548",
    "authentication_configuration_valid": "\u8ba4\u8bc1\u914d\u7f6e\u6709\u6548",
    "knowledge_directory_available": "\u77e5\u8bc6\u5e93\u76ee\u5f55\u53ef\u7528"
}

REMOTE_ENGLISH_TEXT = {
    "remote_access": "Remote Access",
    "local_address": "Local Address",
    "lan_address": "LAN Address",
    "remote_status": "Remote Status",
    "remote_access_enable": "Remote Access Enable",
    "remote_mode": "Remote Mode",
    "network_available": "Network Available",
    "security_status": "Security Status",
    "local_only": "Local Only",
    "auth_required_hint": "Remote access requires authentication.",
    "disabled": "Disabled",
    "unavailable": "Unavailable",
    "yes": "Yes",
    "no": "No",
    "security_checklist": "Security Checklist",
    "remote_health": "Remote Health",
    "remote_access_label": "Remote Access",
    "current_mode": "Current Mode",
    "authentication": "Authentication",
    "public_exposure": "Public Exposure",
    "firewall": "Firewall",
    "network": "Network",
    "local_access": "Local Access",
    "lan_access": "LAN Access",
    "security": "Security",
    "listening_ports": "Listening Ports",
    "none": "None",
    "enabled": "Enabled",
    "required": "Required",
    "not_configured": "Not Configured",
    "unknown": "Unknown",
    "safe": "Safe",
    "warning": "Warning",
    "ok": "OK",
    "available": "Available",
    "local_only_description": "Local Only: only local machine access is allowed.",
    "lan_only_description": "LAN Only: future LAN access support.",
    "secure_remote_description": "Secure Remote: future secure remote access support.",
    "authentication_status": "Authentication Status",
    "configured": "Configured",
    "authentication_not_configured_hint": "Authentication system is not configured yet.",
    "lan_ios_readiness": "LAN / iOS Access Readiness",
    "ios_same_wifi_status": "iOS Same Wi-Fi Access Status",
    "tailscale_readiness": "Tailscale Readiness",
    "remote_safety_status": "Remote Access Safety Status",
    "iphone_same_wifi_access": "iPhone Same Wi-Fi Access",
    "iphone_same_wifi_note": "If iPhone and this PC are connected to the same Wi-Fi, Safari may access the preview URL in the future. This version only generates an address preview, does not start a listening service, and does not guarantee current access.",
    "local_preview": "Local Preview",
    "lan_preview": "LAN Preview",
    "port_not_configured": "Port not configured yet.",
    "no_lan_address": "No LAN address available.",
    "ios_compatibility": "iOS Compatibility",
    "safari_supported": "Safari Supported",
    "android_required": "Android Required",
    "same_wifi_access": "Same Wi-Fi Access",
    "cellular_access": "Cellular Access",
    "future_supported": "Future Supported",
    "requires_secure_tunnel": "Requires Secure Tunnel",
    "tailscale_note": "For cellular access from iPhone, Tailscale or another secure tunnel is recommended.",
    "lan_access_preparation": "LAN Access Preparation",
    "lan_readiness": "LAN Readiness",
    "ios_access": "iOS Access",
    "not_ready": "Not Ready",
    "do_not_expose_warning": "Do not expose Aurora directly to the public internet.\nUse LAN or a secure tunnel such as Tailscale.",
    "safety_gate": "Safety Gate",
    "remote_safety_check": "Remote Access Safety Check",
    "remote_readiness": "Remote Readiness",
    "lan": "LAN",
    "missing": "Missing",
    "confirmed": "Confirmed",
    "not_confirmed": "Not Confirmed",
    "overall": "Overall",
    "blocked": "Blocked",
    "security_confirmation": "Security Confirmation",
    "understand_risk": "I Understand the Risk",
    "remote_access_warning": "Warning:\nRemote access allows other devices to connect to Aurora.\nMake sure authentication and network security are configured.",
    "authentication_required_before_remote": "Authentication is required before enabling remote access.",
    "security_confirmation_required": "Security confirmation is required before enabling remote access.",
    "authentication_required": "Authentication Required",
    "authentication_type": "Authentication Type",
    "token_status": "Token Status",
    "token": "Token",
    "token_auth_future": "Token Authentication (Future)",
    "password_auth_future": "Password Authentication (Future)",
    "auth_secrets_plaintext_warning": "Authentication secrets should not be stored as plain text.",
    "token_authentication": "Token Authentication",
    "setup_token": "Setup Token",
    "token_last_updated": "Token Last Updated",
    "never_configured": "Never configured.",
    "auth_readiness": "Authentication Readiness",
    "token_missing": "Token Missing",
    "token_auth_not_configured": "Token authentication is not configured.",
    "token_setup_note": "This version only creates temporary token status, does not save a real token, and does not persist after closing the app.",
    "never_share_token": "Never share your authentication token.",
    "store_credentials_securely": "Store authentication credentials securely.",
    "credential_storage": "Credential Storage",
    "storage_status": "Storage Status",
    "secure_storage_configured": "Secure Storage Configured",
    "storage_type": "Storage Type",
    "recommended": "Recommended",
    "windows_credential_manager": "Windows Credential Manager",
    "future_option": "Future Option",
    "encrypted_local_storage": "Encrypted Local Storage",
    "not_recommended": "Not Recommended",
    "plain_text_file": "Plain Text File",
    "credential_security": "Credential Security",
    "no_plain_text_storage": "No Plain Text Storage",
    "authentication_framework_ready": "Authentication Framework Ready",
    "secure_storage_not_configured": "Secure Storage Not Configured",
    "storage": "Storage",
    "storage_missing": "Storage Missing",
    "secure_credential_storage_required": "Secure credential storage required.",
    "credential_storage_provider": "Credential Storage Provider",
    "provider": "Provider",
    "status": "Status",
    "test_status": "Test Status",
    "last_check_time": "Last Check",
    "test_secure_storage": "Test Secure Storage",
    "remove_test_credential": "Remove Test Credential",
    "passed": "Passed",
    "failed": "Failed",
    "available_status": "Available",
    "unavailable_status": "Unavailable",
    "secure_storage_unavailable": "Secure credential storage unavailable.",
    "windows_credential_manager_note": "Windows Credential Manager provides secure credential storage."
    ,
    "credential_storage_diagnostics": "Credential Storage Diagnostics",
    "availability": "Availability",
    "last_result": "Last Result",
    "last_error": "Last Error",
    "command_status": "Command Status",
    "credential_history": "Credential Storage History",
    "no_history": "No history",
    "open_diagnostics_for_details": "Open Diagnostics for details.",
    "remote_blocked_storage_unavailable": "Remote access blocked:\nSecure credential storage unavailable.\nOpen Diagnostics for details."
    ,
    "remote_diagnostics": "Remote Diagnostics",
    "remote_readiness_summary": "Remote Readiness Summary",
    "credential_storage_details": "Credential Storage Details",
    "last_operation": "Last Operation",
    "operation_result": "Operation Result",
    "duration": "Duration",
    "error_reason": "Error Reason",
    "suggestion": "Suggestion",
    "release_check": "Release Check",
    "release_check_started": "Release Check Started",
    "release_check_completed": "Release Check Completed",
    "startup_diagnostic": "Startup Diagnostic",
    "features": "Features",
    "remote_security": "Remote Security",
    "data_directory_available": "Data Directory Available",
    "configuration_valid": "Configuration Valid",
    "remote_configuration_valid": "Remote Configuration Valid",
    "authentication_configuration_valid": "Authentication Configuration Valid",
    "knowledge_directory_available": "Knowledge Directory Available"
}

CHINESE_TEXT.update(PERSONA_CHINESE_TEXT)
ENGLISH_TEXT.update(PERSONA_ENGLISH_TEXT)
TEXT.update(PERSONA_CHINESE_TEXT)
CHINESE_TEXT.update(REMOTE_CHINESE_TEXT)
ENGLISH_TEXT.update(REMOTE_ENGLISH_TEXT)
TEXT.update(REMOTE_CHINESE_TEXT)

V2_CHINESE_TEXT = {
    "showcase": "Aurora 展示",
    "showcase_ready": "展示页已准备",
    "local_ai_chat": "本地 AI 聊天",
    "memory_system": "记忆系统",
    "knowledge_base": "知识库",
    "persona_system": "人格系统",
    "context_inspector": "上下文检查器",
    "remote_security_framework": "远程安全框架",
    "lan_status_page": "局域网状态页",
    "start_lan_status_page": "启动局域网状态页",
    "stop_lan_status_page": "停止局域网状态页",
    "copy_lan_url": "复制 LAN 地址",
    "running": "运行中",
    "stopped": "已停止",
    "local_url": "本地地址",
    "lan_url": "局域网地址",
    "iphone_same_wifi_test": "iPhone 同 Wi-Fi 测试",
    "iphone_same_wifi_steps": "1. 确认 iPhone 和电脑连接同一个 Wi-Fi。\n2. 点击启动局域网状态页。\n3. 在 iPhone Safari 输入 LAN 地址。\n4. 如果无法访问，请检查 Windows 防火墙提示。\n\nAurora 不会自动修改防火墙。",
    "lan_status_warning": "启动局域网状态页后，同一 Wi-Fi 下的设备可以查看 Aurora 状态。",
    "lan_status_readonly_note": "这是只读局域网状态页。暂不支持手机聊天。",
    "a_personal_local_ai_assistant": "A Personal Local AI Assistant",
    "core_features": "核心功能",
    "protected": "受保护",
    "lan_server_module_available": "LAN 服务模块可用",
    "lan_status_port_available": "LAN 状态页端口可用",
    "lan_status_page_stopped_by_default": "LAN 状态页默认停止",
    "available_status": "可用",
    "lan_chat": "局域网聊天",
    "start_lan_chat": "启动局域网聊天",
    "stop_lan_chat": "停止局域网聊天",
    "copy_mobile_url": "复制手机地址",
    "mobile_url": "手机地址",
    "mobile_access_confirmation": "手机访问确认",
    "lan_chat_warning": "启动局域网聊天后，同一 Wi-Fi 下的设备可以向 Aurora 发送聊天请求。",
    "mobile_chat_started": "手机聊天已启动",
    "mobile_chat_stopped": "手机聊天已停止",
    "lan_chat_disabled": "局域网聊天已关闭",
    "remote_access_disabled": "远程访问未启用。",
    "lan_chat_enable": "启用局域网聊天",
    "mobile_access_confirm": "确认允许手机局域网访问",
    "lan_chat_disabled_by_default": "局域网聊天默认关闭",
    "mobile_chat_timeout": "手机聊天超时",
    "firewall_notice": "Windows 防火墙可能阻止局域网访问。\n首次运行时请允许 Aurora 网络访问。",
    "copy_failed": "复制失败",
    "port_in_use_hint": "端口已被占用。请关闭其他 Aurora 实例。",
    "request_timeout": "请求超时",
    "ai_response_failed": "AI 回复失败",
    "mobile_debug_mode": "\u624b\u673a\u8c03\u8bd5\u6a21\u5f0f",
    "mobile_response_limit": "\u624b\u673a\u56de\u590d\u663e\u793a\u4e0a\u9650",
    "ollama_unavailable": "Ollama \u4e0d\u53ef\u7528",
    "context_build_failed": "\u4e0a\u4e0b\u6587\u6784\u5efa\u5931\u8d25",
    "chat_generation_failed": "AI \u751f\u6210\u5931\u8d25",
    "invalid_response": "\u8fd4\u56de\u683c\u5f0f\u9519\u8bef",
    "unknown_error": "\u672a\u77e5\u9519\u8bef",
    "ai_ready": "AI \u5c31\u7eea",
    "ai_unavailable": "AI \u4e0d\u53ef\u7528",
    "selected_network_adapter": "\u5df2\u9009\u7f51\u7edc\u9002\u914d\u5668",
    "selected_lan_ip": "\u5df2\u9009 LAN IP",
    "mobile_debug_panel": "\u624b\u673a\u8c03\u8bd5\u9762\u677f",
    "client": "\u5ba2\u6237\u7aef",
    "stage": "\u9636\u6bb5",
    "duration": "\u8017\u65f6",
    "model_name": "\u6a21\u578b\u540d\u79f0",
    "ollama_url": "Ollama URL",
    "error": "\u9519\u8bef",
    "preferred_interface": "\u9996\u9009\u7f51\u5361",
    "ignore_virtual_adapter": "\u5ffd\u7565\u865a\u62df\u7f51\u5361",
    "model_unavailable": "\u6a21\u578b\u4e0d\u53ef\u7528",
    "ai_configuration": "AI \u914d\u7f6e",
    "chat_model": "\u804a\u5929\u6a21\u578b",
    "embedding_model": "Embedding \u6a21\u578b",
    "model_capability": "\u6a21\u578b\u80fd\u529b",
    "rejected_interfaces": "\u5df2\u6392\u9664\u7f51\u7edc\u63a5\u53e3",
    "model_cannot_chat": "\u5f53\u524d\u6a21\u578b\u4e0d\u652f\u6301\u804a\u5929\uff0c\u8bf7\u9009\u62e9\u804a\u5929\u6a21\u578b\u3002",
    "mobile_chat": "\u624b\u673a\u804a\u5929",
    "error": "\u9519\u8bef"
}

V2_ENGLISH_TEXT = {
    "showcase": "Aurora Showcase",
    "showcase_ready": "Showcase Ready",
    "local_ai_chat": "Local AI Chat",
    "memory_system": "Memory System",
    "knowledge_base": "Knowledge Base",
    "persona_system": "Persona System",
    "context_inspector": "Context Inspector",
    "remote_security_framework": "Remote Security Framework",
    "lan_status_page": "LAN Status Page",
    "start_lan_status_page": "Start LAN Status Page",
    "stop_lan_status_page": "Stop LAN Status Page",
    "copy_lan_url": "Copy LAN URL",
    "running": "Running",
    "stopped": "Stopped",
    "local_url": "Local URL",
    "lan_url": "LAN URL",
    "iphone_same_wifi_test": "iPhone Same Wi-Fi Test",
    "iphone_same_wifi_steps": "1. Make sure iPhone and this PC use the same Wi-Fi.\n2. Click Start LAN Status Page.\n3. Enter the LAN URL in iPhone Safari.\n4. If it cannot be reached, check the Windows Firewall prompt.\n\nAurora does not modify the firewall automatically.",
    "lan_status_warning": "Starting LAN Status Page allows devices on the same Wi-Fi to view Aurora status.",
    "lan_status_readonly_note": "This is a read-only LAN status page. Chat is not available on mobile yet.",
    "a_personal_local_ai_assistant": "A Personal Local AI Assistant",
    "core_features": "Core Features",
    "protected": "Protected",
    "lan_server_module_available": "LAN Server Module Available",
    "lan_status_port_available": "LAN Status Port Available",
    "lan_status_page_stopped_by_default": "LAN Status Page Stopped by Default",
    "available_status": "Available",
    "lan_chat": "LAN Chat",
    "start_lan_chat": "Start LAN Chat",
    "stop_lan_chat": "Stop LAN Chat",
    "copy_mobile_url": "Copy Mobile URL",
    "mobile_url": "Mobile URL",
    "mobile_access_confirmation": "Mobile Access Confirmation",
    "lan_chat_warning": "Starting LAN Chat allows devices on the same Wi-Fi to send chat requests to Aurora.",
    "mobile_chat_started": "Mobile Chat Started",
    "mobile_chat_stopped": "Mobile Chat Stopped",
    "lan_chat_disabled": "LAN Chat Disabled",
    "remote_access_disabled": "Remote Access Disabled",
    "lan_chat_enable": "LAN Chat Enable",
    "mobile_access_confirm": "Confirm Mobile LAN Access",
    "lan_chat_disabled_by_default": "LAN Chat Disabled by Default",
    "mobile_chat_timeout": "Mobile Chat Timeout",
    "firewall_notice": "Windows Firewall may block LAN access.\nPlease allow Aurora when prompted.",
    "copy_failed": "Copy failed",
    "port_in_use_hint": "Port already in use. Please close other Aurora instances.",
    "request_timeout": "Request Timeout",
    "ai_response_failed": "AI Response Failed",
    "mobile_debug_mode": "Mobile Debug Mode",
    "mobile_response_limit": "Mobile Response Display Limit",
    "ollama_unavailable": "Ollama Unavailable",
    "context_build_failed": "Context Build Failed",
    "chat_generation_failed": "Chat Generation Failed",
    "invalid_response": "Invalid Response",
    "unknown_error": "Unknown Error",
    "ai_ready": "AI Ready",
    "ai_unavailable": "AI Unavailable",
    "selected_network_adapter": "Selected Network Adapter",
    "selected_lan_ip": "Selected LAN IP",
    "mobile_debug_panel": "Mobile Debug Panel",
    "client": "Client",
    "stage": "Stage",
    "duration": "Duration",
    "model_name": "Model Name",
    "ollama_url": "Ollama URL",
    "error": "Error",
    "preferred_interface": "Preferred Interface",
    "ignore_virtual_adapter": "Ignore Virtual Adapter",
    "model_unavailable": "Model Unavailable",
    "ai_configuration": "AI Configuration",
    "chat_model": "Chat Model",
    "embedding_model": "Embedding Model",
    "model_capability": "Model Capability",
    "rejected_interfaces": "Rejected Interfaces",
    "model_cannot_chat": "Model cannot chat. Please select a chat model.",
    "mobile_chat": "Mobile Chat",
    "error": "Error"
}

CHINESE_TEXT.update(V2_CHINESE_TEXT)
ENGLISH_TEXT.update(V2_ENGLISH_TEXT)
TEXT.update(V2_CHINESE_TEXT)


def set_language(language):
    """Switch the shared text mapping for subsequently created UI widgets."""
    source = ENGLISH_TEXT if str(language).casefold() == "english" else CHINESE_TEXT
    TEXT.clear()
    TEXT.update(source)
