"""Compatibility text mapping for legacy UI code.

New UI text should use modules.i18n.t(). This module keeps the existing
TEXT / set_language API stable while avoiding startup failures from missing
or damaged translation keys.
"""

from modules.i18n import normalize_language, set_language as set_i18n_language, t


class TextDict(dict):
    def __missing__(self, key):
        value = str(key).replace("_", " ").title()
        self[key] = value
        return value


BASE_KEYS = [
    "system_status",
    "startup_status",
    "quick_actions",
    "recent_log",
    "models",
    "chat",
    "memory",
    "settings",
    "health",
    "about",
    "exit",
    "model_selector",
    "conversation_list",
    "input_box",
    "send",
    "clear",
    "stop_generate",
    "new_chat",
    "save_chat",
    "rename_chat",
    "delete_chat",
    "close",
    "memory_list",
    "add",
    "edit",
    "delete",
    "type",
    "content",
    "importance",
    "appearance",
    "theme",
    "ollama_host",
    "refresh_interval",
    "health_dashboard",
    "refresh",
    "test",
    "save",
    "ready",
    "checking",
    "online",
    "offline",
    "all_ready",
    "name",
    "id",
    "size",
    "modified",
    "no_models",
    "no_conversations",
    "last_check",
    "no_logs",
    "about_title",
    "enabled",
    "disabled",
    "yes",
    "no",
    "unavailable",
    "unknown",
    "none",
    "error",
    "warning",
    "ok",
    "available",
    "configured",
    "not_configured",
    "missing",
    "confirmed",
    "not_confirmed",
    "blocked",
    "passed",
    "failed",
    "running",
    "stopped"
]

EXTRA_TEXT = {
    "system_status": "System Status",
    "startup_status": "Startup Status",
    "quick_actions": "Quick Actions",
    "recent_log": "Recent Log",
    "models": "Models",
    "chat": "Chat",
    "memory": "Memory",
    "settings": "Settings",
    "health": "Health",
    "about": "About",
    "exit": "Exit",
    "model_selector": "Model Selector",
    "conversation_list": "Conversation List",
    "input_box": "Input Box",
    "send": "Send",
    "clear": "Clear",
    "stop_generate": "Stop Generate",
    "new_chat": "New Chat",
    "save_chat": "Save Chat",
    "rename_chat": "Rename Chat",
    "delete_chat": "Delete Chat",
    "close": "Close",
    "memory_list": "Memory List",
    "add": "Add",
    "edit": "Edit",
    "delete": "Delete",
    "type": "Type",
    "content": "Content",
    "importance": "Importance",
    "appearance": "Appearance",
    "theme": "Theme",
    "ollama_host": "Ollama Host",
    "refresh_interval": "Status Refresh Interval",
    "health_dashboard": "Health Dashboard",
    "refresh": "Refresh",
    "test": "Test",
    "save": "Save",
    "ready": "Ready",
    "checking": "Checking...",
    "online": "Online",
    "offline": "Offline",
    "all_ready": "All Systems Ready",
    "name": "Name",
    "id": "ID",
    "size": "Size",
    "modified": "Modified",
    "no_models": "No Ollama models found.",
    "no_conversations": "No saved conversations",
    "last_check": "Last Check Time",
    "no_logs": "No recent logs",
    "about_title": "About",
    "persona": "Persona",
    "persona_name": "Name",
    "persona_description": "Description",
    "persona_style": "Style",
    "persona_rules": "Rules",
    "edit_persona": "Edit Persona",
    "save_persona": "Save Persona",
    "reset_persona": "Reset Default",
    "persona_enable": "Persona Enable",
    "showcase": "Aurora Showcase",
    "showcase_ready": "Showcase Ready",
    "local_ai_chat": "Local AI Chat",
    "memory_system": "Memory System",
    "knowledge_base": "Knowledge Base",
    "persona_system": "Persona System",
    "context_inspector": "Context Inspector",
    "remote_security": "Remote Security",
    "protected": "Protected",
    "available_status": "Available",
    "remote_access": "Remote Access",
    "remote_diagnostics": "Remote Diagnostics",
    "remote_access_enable": "Remote Access Enable",
    "remote_mode": "Remote Mode",
    "preferred_interface": "Preferred Interface",
    "ignore_virtual_adapter": "Ignore Virtual Adapter",
    "lan_chat_enable": "LAN Chat Enable",
    "mobile_access_confirm": "Confirm Mobile LAN Access",
    "mobile_chat_timeout": "Mobile Chat Timeout",
    "mobile_debug_mode": "Mobile Debug Mode",
    "mobile_response_limit": "Mobile Response Display Limit",
    "chat_model": "Chat Model",
    "embedding_model": "Embedding Model",
    "model_capability": "Model Capability",
    "selected_network_adapter": "Selected Network Adapter",
    "selected_lan_ip": "Selected LAN IP",
    "rejected_interfaces": "Rejected Interfaces",
    "local_address": "Local Address",
    "lan_address": "LAN Address",
    "network_available": "Network Available",
    "remote_status": "Remote Status",
    "security_status": "Security Status",
    "local_only": "Local Only",
    "auth_required_hint": "Remote access requires authentication.",
    "do_not_expose_warning": "Do not expose Aurora directly to the public internet.",
    "safety_gate": "Safety Gate",
    "remote_safety_check": "Remote Access Safety Check",
    "remote_access_warning": "Remote access allows other devices to connect to Aurora. Confirm authentication and network safety first.",
    "network": "Network",
    "lan": "LAN",
    "required": "Required",
    "overall": "Overall",
    "security_confirmation": "Security Confirmation",
    "lan_ios_readiness": "LAN / iOS Access Readiness",
    "ios_same_wifi_status": "iOS Same Wi-Fi Status",
    "tailscale_readiness": "Tailscale Readiness",
    "remote_safety_status": "Remote Safety Status",
    "local_preview": "Local Preview",
    "lan_preview": "LAN Preview",
    "iphone_same_wifi_access": "iPhone Same Wi-Fi Access",
    "iphone_same_wifi_note": "Use the same Wi-Fi network and open the LAN URL in Safari.",
    "ios_compatibility": "iOS Compatibility",
    "safari_supported": "Safari Supported",
    "android_required": "Android Required",
    "same_wifi_access": "Same Wi-Fi Access",
    "cellular_access": "Cellular Access",
    "future_supported": "Future Supported",
    "requires_secure_tunnel": "Requires Secure Tunnel",
    "tailscale_note": "Use Tailscale or another secure tunnel for cellular access.",
    "lan_access_preparation": "LAN Access Preparation",
    "lan_status_page": "LAN Status Page",
    "lan_chat": "LAN Chat",
    "mobile_url": "Mobile URL",
    "mobile_access_confirmation": "Mobile Access Confirmation",
    "ai_configuration": "AI Configuration",
    "mobile_chat": "Mobile Chat",
    "mobile_debug_panel": "Mobile Debug Panel",
    "client": "Client",
    "stage": "Stage",
    "duration": "Duration",
    "model_name": "Model Name",
    "ollama_url": "Ollama URL",
    "firewall_notice": "Windows Firewall may block LAN access. Allow Aurora when prompted.",
    "iphone_same_wifi_test": "iPhone Same Wi-Fi Test",
    "iphone_same_wifi_steps": "1. Connect iPhone and this PC to the same Wi-Fi.\n2. Start LAN Chat.\n3. Open the mobile URL in iPhone Safari.",
    "security_checklist": "Security Checklist",
    "remote_access_label": "Remote Access",
    "current_mode": "Current Mode",
    "authentication": "Authentication",
    "public_exposure": "Public Exposure",
    "firewall": "Firewall",
    "remote_health": "Remote Health",
    "local_access": "Local Access",
    "lan_access": "LAN Access",
    "lan_readiness": "LAN Readiness",
    "ios_access": "iOS Access",
    "authentication_status": "Authentication Status",
    "authentication_required": "Authentication Required",
    "authentication_type": "Authentication Type",
    "token_status": "Token Status",
    "token": "Token",
    "token_last_updated": "Token Last Updated",
    "never_configured": "Never configured",
    "token_authentication": "Token Authentication",
    "token_auth_future": "Token Authentication (Future)",
    "password_auth_future": "Password Authentication (Future)",
    "auth_secrets_plaintext_warning": "Authentication secrets should not be stored as plain text.",
    "token_setup_note": "This version only marks temporary token status and does not store real tokens.",
    "never_share_token": "Never share your authentication token.",
    "store_credentials_securely": "Store credentials securely.",
    "setup_token": "Setup Token",
    "credential_storage": "Credential Storage",
    "storage_status": "Storage Status",
    "secure_storage_configured": "Secure Storage Configured",
    "storage_type": "Storage Type",
    "recommended": "Recommended",
    "windows_credential_manager": "Windows Credential Manager",
    "future_option": "Future Option",
    "encrypted_local_storage": "Encrypted Local Storage",
    "not_recommended": "Not Recommended",
    "plain_text_file": "Plain Text File",
    "credential_storage_provider": "Credential Storage Provider",
    "provider": "Provider",
    "status": "Status",
    "test_status": "Test Status",
    "last_check_time": "Last Check Time",
    "test_secure_storage": "Test Secure Storage",
    "remove_test_credential": "Remove Test Credential",
    "last_operation": "Last Operation",
    "operation_result": "Operation Result",
    "error_reason": "Error Reason",
    "suggestion": "Suggestion",
    "release_check": "Release Check",
    "remote_readiness_summary": "Remote Readiness Summary",
    "credential_storage_details": "Credential Storage Details",
    "credential_storage_diagnostics": "Credential Storage Diagnostics",
    "availability": "Availability",
    "command_status": "Command Status",
    "last_result": "Last Result",
    "last_error": "Last Error",
    "credential_history": "Credential History",
    "credential_security": "Credential Security",
    "no_plain_text_storage": "No Plain Text Storage",
    "authentication_framework_ready": "Authentication Framework Ready",
    "secure_storage_not_configured": "Secure storage not configured",
    "listening_ports": "Listening Ports",
    "start_lan_status_page": "Start LAN Status Page",
    "stop_lan_status_page": "Stop LAN Status Page",
    "copy_lan_url": "Copy LAN URL",
    "start_lan_chat": "Start LAN Chat",
    "stop_lan_chat": "Stop LAN Chat",
    "copy_mobile_url": "Copy Mobile URL",
    "lan_status_warning": "Starting LAN Status Page allows devices on the same Wi-Fi to view Aurora status.",
    "lan_chat_warning": "Starting LAN Chat allows devices on the same Wi-Fi to send chat requests to Aurora.",
    "security_confirmation_required": "Security confirmation is required before enabling remote access.",
    "mobile_chat_started": "Mobile Chat Started",
    "mobile_chat_stopped": "Mobile Chat Stopped",
    "copy_failed": "Copy failed",
    "storage_missing": "Storage Missing",
    "unavailable_status": "Unavailable",
    "safe": "Safe",
    "remove_test_credential": "Remove Test Credential",
    "a_personal_local_ai_assistant": "A Personal Local AI Assistant",
    "core_features": "Core Features",
    "model_cannot_chat": "Model cannot chat. Please select a chat model.",
    "remote_blocked_storage_unavailable": "Remote access blocked: secure credential storage unavailable.",
    "secure_credential_storage_required": "Secure credential storage is required.",
    "authentication_required_before_remote": "Authentication is required before enabling remote access."
}


def _build_text(language):
    set_i18n_language(language)
    data = TextDict(EXTRA_TEXT)
    for key in BASE_KEYS:
        data[key] = t(key, data.get(key, key.replace("_", " ").title()))
    return data


TEXT = TextDict(_build_text("zh_CN"))
CHINESE_TEXT = TextDict(_build_text("zh_CN"))
ENGLISH_TEXT = TextDict(_build_text("en_US"))


def set_language(language):
    normalized = normalize_language(language)
    set_i18n_language(normalized)
    source = ENGLISH_TEXT if normalized == "en_US" else CHINESE_TEXT
    TEXT.clear()
    TEXT.update(source)
