"""Data contracts shared by replaceable STT and TTS providers."""

from __future__ import annotations

from dataclasses import dataclass, field
from threading import Event
from typing import Callable, Iterator, Literal, Mapping


AudioInputKind = Literal["microphone", "file", "bytes"]


@dataclass(frozen=True)
class AudioInput:
    """Audio supplied to an STT provider, without recording concerns."""

    kind: AudioInputKind
    path: str | None = None
    data: bytes | None = None
    sample_rate: int | None = None
    language_hint: str | None = None
    duration_ms: int = 0
    diagnostics: Mapping[str, object] = field(default_factory=dict)


@dataclass(frozen=True)
class TranscriptionResult:
    """Provider output containing text and optional recognition diagnostics."""

    text: str
    language: str = ""
    confidence: float | None = None
    duration_ms: int = 0
    diagnostics: Mapping[str, object] = field(default_factory=dict)


@dataclass(frozen=True)
class VoiceOptions:
    """Provider-neutral voice selection and style options."""

    voice: str = ""
    language: str = "zh_CN"
    rate: float = 1.0
    style: str = ""


@dataclass(frozen=True)
class TTSRequest:
    """Provider-neutral synthesis request used by the TTS routing boundary."""

    text: str
    options: VoiceOptions = field(default_factory=VoiceOptions)
    timeout_seconds: float | None = None
    cancel_event: Event | None = field(default=None, repr=False, compare=False)
    provider: str | None = None


@dataclass(frozen=True)
class SpeechResult:
    """Audio generated by a TTS provider, before playback."""

    audio_path: str | None = None
    audio_bytes: bytes | None = None
    mime_type: str = "audio/wav"
    duration_ms: int = 0
    diagnostics: Mapping[str, object] = field(default_factory=dict)


@dataclass
class StreamingSpeechResult:
    """Incremental PCM returned by a streaming-capable TTS provider."""

    metadata: Mapping[str, object]
    chunks: Iterator[bytes]
    diagnostics: dict[str, object] = field(default_factory=dict)
    _close: Callable[[], None] = field(default=lambda: None, repr=False, compare=False)

    def close(self) -> None:
        self._close()

    cancel = close

    def __enter__(self) -> "StreamingSpeechResult":
        return self

    def __exit__(self, *_args: object) -> bool:
        self.close()
        return False


# Canonical response name for the provider layer; SpeechResult remains the
# compatibility name used by playback and existing integrations.
TTSResponse = SpeechResult
